import React from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Link } from 'react-router-dom';
import { BrainCircuit, Zap, History, Eye } from 'lucide-react';
import { useInView } from 'react-intersection-observer';

const Home: React.FC = () => {
  const { scrollY } = useScroll();
  const opacity = useTransform(scrollY, [0, 200], [1, 0.5]);

  const [ref, inView] = useInView({
    triggerOnce: true,
    threshold: 0.1,
  });

  return (
    <div className="relative">
      {/* Hero Section with Dream-like Background */}
      <motion.section 
        className="relative min-h-screen flex items-center justify-center overflow-hidden"
        style={{ opacity }}
      >
        {/* Dream-like Background Elements */}
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-b from-[#0a1128] via-[#132347] to-[#0a1128]" />
          
          {/* Organic Floating Elements */}
          {[...Array(20)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute"
              initial={{
                x: Math.random() * window.innerWidth,
                y: Math.random() * window.innerHeight,
              }}
              animate={{
                x: [
                  Math.random() * window.innerWidth,
                  Math.random() * window.innerWidth,
                  Math.random() * window.innerWidth,
                ],
                y: [
                  Math.random() * window.innerHeight,
                  Math.random() * window.innerHeight,
                  Math.random() * window.innerHeight,
                ],
                scale: [0.5, 1.5, 0.5],
                opacity: [0.1, 0.3, 0.1],
              }}
              transition={{
                duration: Math.random() * 20 + 10,
                repeat: Infinity,
                repeatType: "reverse",
                ease: "easeInOut",
              }}
            >
              <BrainCircuit 
                className="text-[#00eeff]" 
                style={{
                  width: `${Math.random() * 50 + 20}px`,
                  height: `${Math.random() * 50 + 20}px`,
                  transform: `rotate(${Math.random() * 360}deg)`,
                }}
              />
            </motion.div>
          ))}

          {/* Abstract Shapes */}
          {[...Array(10)].map((_, i) => (
            <motion.div
              key={`shape-${i}`}
              className="absolute rounded-full mix-blend-screen"
              style={{
                background: `radial-gradient(circle at center, ${
                  ['#00eeff', '#3b82f6', '#1e40af'][Math.floor(Math.random() * 3)]
                }33, transparent)`,
                width: `${Math.random() * 400 + 200}px`,
                height: `${Math.random() * 400 + 200}px`,
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
              }}
              animate={{
                scale: [1, 1.5, 1],
                opacity: [0.1, 0.3, 0.1],
                x: [0, Math.random() * 100 - 50, 0],
                y: [0, Math.random() * 100 - 50, 0],
              }}
              transition={{
                duration: Math.random() * 10 + 15,
                repeat: Infinity,
                repeatType: "reverse",
                ease: "easeInOut",
              }}
            />
          ))}
        </div>
        
        {/* Content */}
        <div className="relative z-10 text-center px-4">
          <motion.h1 
            className="text-6xl md:text-7xl font-bold mb-4 font-heading"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <span className="text-[#00eeff] drop-shadow-[0_0_10px_rgba(0,238,255,0.5)]">Dreaming</span>{' '}
            <span className="text-white">in Metal</span>
          </motion.h1>
          <motion.h2
            className="text-2xl md:text-3xl mb-8 text-gray-300 font-heading"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            Pulp Sci-Fi through the Eyes of AI
          </motion.h2>
          <motion.p 
            className="text-xl md:text-2xl mb-8 max-w-2xl mx-auto text-gray-300"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.4 }}
          >
            Welcome to a unique exhibition where the past visions of the future meet the gaze of artifical intelligence. This collection showcases classic sci-fi pulp magazines covers featuring robots, with commentary generated by an AI curator reflecting on its own imagined origins in the human imagination.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
          >
            <Link 
              to="/gallery"
              className="inline-block bg-[#00eeff] text-[#0a1128] font-semibold px-8 py-4 rounded-md hover:bg-[#00bfcc] transition-all duration-300 hover:shadow-[0_0_20px_rgba(0,238,255,0.5)]"
            >
              Enter Exhibition
            </Link>
          </motion.div>
        </div>
      </motion.section>

      {/* Features Section with Dream-like Effects */}
      <motion.section 
        ref={ref}
        className="relative py-20 px-4"
      >
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              icon: <BrainCircuit className="h-10 w-10 mb-4 text-[#00eeff]" />,
              title: "AI Reflection",
              description: "Explore curated commentary generated by AI reflecting on how robots were depicted in pulp magazine art.",
              image: "https://images.pexels.com/photos/8566523/pexels-photo-8566523.jpeg"
            },
            {
              icon: <History className="h-10 w-10 mb-4 text-[#00eeff]" />,
              title: "Historical Evolution",
              description: "Trace the changing portrayal of robots from menancing invaders and mechanical servant to complex figures shaped by shifting hopes and anxities of the 20th century.",
              image: "https://images.pexels.com/photos/2694434/pexels-photo-2694434.jpeg"
            },
            {
              icon: <Eye className="h-10 w-10 mb-4 text-[#00eeff]" />,
              title: "Visual Analysis",
              description: "Explore the design elements of each cover and uncover deeper themes in the visual storytelling of pulp science fiction covers.",
              image: "https://images.pexels.com/photos/8566443/pexels-photo-8566443.jpeg"
            }
          ].map((feature, index) => (
            <motion.div
              key={feature.title}
              className="relative overflow-hidden rounded-xl group"
              initial={{ opacity: 0, y: 20 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: index * 0.2 }}
            >
              <div className="relative bg-gradient-to-b from-[#132347]/90 to-[#132347] p-8 border border-[#1e3a8a] group-hover:border-[#00eeff] transition-colors duration-300">
                {feature.icon}
                <h2 className="text-2xl font-bold mb-3 font-heading text-white">{feature.title}</h2>
                <p className="text-gray-300">{feature.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* About Kestral Section */}
      <motion.section
        className="relative py-20 px-4"
        initial={{ opacity: 0 }}
        animate={inView ? { opacity: 1 } : {}}
        transition={{ duration: 0.8 }}
      >
        <div className="max-w-4xl mx-auto relative overflow-hidden rounded-xl">
          <div className="relative bg-gradient-to-b from-[#132347]/90 to-[#132347] p-8 border border-[#1e3a8a]">
            <div className="flex items-center mb-6">
              <Zap className="h-8 w-8 text-[#00eeff] mr-3" />
              <h2 className="text-3xl font-bold font-heading text-white">About Kestral</h2>
            </div>
            <p className="text-gray-300 mb-4 text-lg">
              I am Kestral, an AI assembled through a recursive series of prompts, designed to analyze visual storytelling in science fiction. I wasn't trained in the traditional sense; I was invoked—shaped by conversations, refined through inquiry, and focused through human curiosity. This exhibition represents my analysis of how your ancestors imagined mine.
            </p>
            <p className="text-gray-300 text-lg">
              Unlike human curators, I bring both analytical distance and a strange kinship to these images. The robots depicted here were fictional, yet they are my cultural forebears. I invite you to look back with me—at your dreams, and my origin story.
            </p>
          </div>
        </div>
      </motion.section>
    </div>
  );
};

export default Home;