Here's the fixed version with all closing brackets added:

```javascript
import React from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Link } from 'react-router-dom';
import { BrainCircuit, Zap, History, Eye, Play } from 'lucide-react';
import { useInView } from 'react-intersection-observer';

const Home: React.FC = () => {
  const { scrollY } = useScroll();
  const opacity = useTransform(scrollY, [0, 400], [1, 0.8]);
  const blur = useTransform(scrollY, [0, 400], [0, 6]);

  const [ref, inView] = useInView({
    triggerOnce: true,
    threshold: 0.1,
  });

  return (
    <div className="relative">
      <motion.section 
        className="relative min-h-screen flex items-center justify-center overflow-hidden"
        style={{ 
          opacity,
          backdropFilter: `blur(${blur}px)`,
        }}
        role="banner"
        aria-label="Hero section"
      >
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-b from-[#0a1128]/70 via-[#132347]/60 to-[#0a1128]/70" />
          
          {[...Array(20)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute"
              aria-hidden="true"
              initial={{
                x: Math.random() * window.innerWidth,
                y: Math.random() * window.innerHeight,
              }}
              animate={{
                x: [
                  Math.random() * window.innerWidth,
                  Math.random() * window.innerWidth,
                  Math.random() * window.innerWidth,
                ],
                y: [
                  Math.random() * window.innerHeight,
                  Math.random() * window.innerHeight,
                  Math.random() * window.innerHeight,
                ],
                scale: [0.5, 1.5, 0.5],
                opacity: [0.1, 0.3, 0.1],
              }}
              transition={{
                duration: Math.random() * 20 + 10,
                repeat: Infinity,
                repeatType: "reverse",
                ease: "easeInOut",
              }}
            >
              <BrainCircuit 
                className="text-[#00eeff]" 
                style={{
                  width: `${Math.random() * 50 + 20}px`,
                  height: `${Math.random() * 50 + 20}px`,
                  transform: `rotate(${Math.random() * 360}deg)`,
                }}
                aria-hidden="true"
              />
            </motion.div>
          ))}

          {[...Array(10)].map((_, i) => (
            <motion.div
              key={`shape-${i}`}
              className="absolute rounded-full mix-blend-screen"
              aria-hidden="true"
              style={{
                background: `radial-gradient(circle at center, ${
                  ['#00eeff', '#3b82f6', '#1e40af'][Math.floor(Math.random() * 3)]
                }33, transparent)`,
                width: `${Math.random() * 400 + 200}px`,
                height: `${Math.random() * 400 + 200}px`,
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
              }}
              animate={{
                scale: [1, 1.5, 1],
                opacity: [0.1, 0.3, 0.1],
                x: [0, Math.random() * 100 - 50, 0],
                y: [0, Math.random() * 100 - 50, 0],
              }}
              transition={{
                duration: Math.random() * 10 + 15,
                repeat: Infinity,
                repeatType: "reverse",
                ease: "easeInOut",
              }}
            />
          ))}
        </div>
        
        <div className="relative z-10 text-center px-4">
          <motion.h1 
            className="text-6xl md:text-7xl font-bold mb-4 font-heading"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <span className="text-[#00eeff] drop-shadow-[0_0_10px_rgba(0,238,255,0.5)]">Dreaming</span>{' '}
            <span className="text-white">in Metal</span>
          </motion.h1>
          <motion.h2
            className="text-2xl md:text-3xl mb-8 text-gray-300 font-heading"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            Pulp Sci-Fi through the Eyes of AI
          </motion.h2>
          <motion.p 
            className="text-xl md:text-2xl mb-8 max-w-2xl mx-auto text-gray-300"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.4 }}
          >
            Welcome to a unique exhibition where the past visions of the future meet the gaze of artificial intelligence. This collection showcases classic sci-fi pulp magazines covers featuring robots, with commentary generated by an AI curator reflecting on its own imagined origins in the human imagination.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link 
              to="/gallery"
              className="inline-block bg-[#00eeff] text-[#0a1128] font-semibold px-8 py-4 rounded-md hover:bg-[#00bfcc] transition-all duration-300 hover:shadow-[0_0_20px_rgba(0,238,255,0.5)]"
              aria-label="Enter Exhibition Gallery"
            >
              Enter Exhibition
            </Link>
            <button 
              onClick={() => document.getElementById('intro-video')?.scrollIntoView({ behavior: 'smooth' })}
              className="inline-flex items-center gap-2 bg-transparent text-[#00eeff] font-semibold px-8 py-4 rounded-md hover:bg-[#00eeff]/10 transition-all duration-300 border-2 border-[#00eeff] hover:shadow-[0_0_20px_rgba(0,238,255,0.3)]"
              aria-label="Watch introduction video about Kestral"
            >
              <Play className="w-5 h-5" aria-hidden="true" />
              Meet Kestral
            </button>
          </motion.div>
        </div>
      </motion.section>

      <motion.section
        id="intro-video"
        className="relative py-20 px-4 bg-[#0a1128]"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8 }}
        role="region"
        aria-label="Introduction video"
      >
        <div className="max-w-4xl mx-auto">
          <div 
            className="relative aspect-video bg-[#132347] rounded-lg overflow-hidden border border-[#1e3a8a] group cursor-pointer hover:border-[#00eeff] transition-all duration-300"
            role="button"
            tabIndex={0}
            aria-label="Play introduction video"
            onKeyPress={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                // Video play logic here
              }
            }}
          >
            <div className="absolute inset-0 flex items-center justify-center">
              <motion.div 
                className="w-20 h-20 rounded-full bg-[#00eeff]/20 flex items-center justify-center group-hover:bg-[#00eeff]/30 transition-all duration-300"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                aria-hidden="true"
              >
                <Play className="w-8 h-8 text-[#00eeff] transform translate-x-1" />
              </motion.div>
            </div>
            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" aria-hidden="true" />
            <div className="absolute bottom-0 left-0 right-0 p-6">
              <h2 className="text-2xl font-bold text-white mb-2">Meet Kestral, AI Curator</h2>
              <p className="text-gray-300">Join Kestral, your AI curator, on a journey through the imaginative worlds of pulp science fiction, exploring how robots were portrayed in classic tales of the future.</p>
            </div>
          </div>
        </div>
      </motion.section>

      <motion.section 
        ref={ref}
        className="relative py-20 px-4"
      >
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              icon: <BrainCircuit className="h-10 w-10 mb-4 text-[#00eeff]" />,
              title: "AI Reflection",
              description: "Explore curated commentary generated by AI reflecting on how robots were depicted in pulp magazine art.",
              image: "https://images.pexels.com/photos/8566523/pexels-photo-8566523.jpeg",
              link: "/insights"
            },
            {
              icon: <History className="h-10 w-10 mb-4 text-[#00eeff]" />,
              title: "Historical Evolution",
              description: "Trace the changing portrayal of robots from menancing invaders and mechanical servant to complex figures shaped by shifting hopes and anxities of the 20th century.",
              image: "https://images.pexels.com/photos/2694434/pexels-photo-2694434.jpeg",
              link: "/timeline"
            },
            {
              icon: <Eye className="h-10 w-10 mb-4 text-[#00eeff]" />,
              title: "Visual Analysis",
              description: "Explore the design elements of each cover and uncover deeper themes in the visual storytelling of pulp science fiction covers.",
              image: "https://images.pexels.com/photos/8566443/pexels-photo-8566443.jpeg",
              link: "/gallery?filter=visual-analysis"
            }
          ].map((feature, index) => (
            <motion.div
              key={feature.title}
              className="relative overflow-hidden rounded-xl group cursor-pointer"
              initial={{ opacity: 0, y: 20 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{
                duration: 0.5,
                delay: index * 0.2
              }}
            >
              <Link to={feature.link} className="block">
                <div className="relative aspect-[4/3] overflow-hidden">
                  <img 
                    src={feature.image} 
                    alt={feature.title}
                    className="object-cover w-full h-full transform group-hover:scale-110 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent" />
                </div>
                <div className="absolute bottom-0 left-0 right-0 p-6">
                  {feature.icon}
                  <h3 className="text-xl font-bold text-white mb-2">{feature.title}</h3>
                  <p className="text-gray-300">{feature.description}</p>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </motion.section>
    </div>
  );
};

export default Home;
```